// Generated by gencpp from file lkh_tsp_solver/SolveTSP.msg
// DO NOT EDIT!


#ifndef LKH_TSP_SOLVER_MESSAGE_SOLVETSP_H
#define LKH_TSP_SOLVER_MESSAGE_SOLVETSP_H

#include <ros/service_traits.h>


#include <lkh_tsp_solver/SolveTSPRequest.h>
#include <lkh_tsp_solver/SolveTSPResponse.h>


namespace lkh_tsp_solver
{

struct SolveTSP
{

typedef SolveTSPRequest Request;
typedef SolveTSPResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveTSP
} // namespace lkh_tsp_solver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lkh_tsp_solver::SolveTSP > {
  static const char* value()
  {
    return "5b562e6076c8d155d3ad455cb6275b9e";
  }

  static const char* value(const ::lkh_tsp_solver::SolveTSP&) { return value(); }
};

template<>
struct DataType< ::lkh_tsp_solver::SolveTSP > {
  static const char* value()
  {
    return "lkh_tsp_solver/SolveTSP";
  }

  static const char* value(const ::lkh_tsp_solver::SolveTSP&) { return value(); }
};


// service_traits::MD5Sum< ::lkh_tsp_solver::SolveTSPRequest> should match
// service_traits::MD5Sum< ::lkh_tsp_solver::SolveTSP >
template<>
struct MD5Sum< ::lkh_tsp_solver::SolveTSPRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lkh_tsp_solver::SolveTSP >::value();
  }
  static const char* value(const ::lkh_tsp_solver::SolveTSPRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lkh_tsp_solver::SolveTSPRequest> should match
// service_traits::DataType< ::lkh_tsp_solver::SolveTSP >
template<>
struct DataType< ::lkh_tsp_solver::SolveTSPRequest>
{
  static const char* value()
  {
    return DataType< ::lkh_tsp_solver::SolveTSP >::value();
  }
  static const char* value(const ::lkh_tsp_solver::SolveTSPRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lkh_tsp_solver::SolveTSPResponse> should match
// service_traits::MD5Sum< ::lkh_tsp_solver::SolveTSP >
template<>
struct MD5Sum< ::lkh_tsp_solver::SolveTSPResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lkh_tsp_solver::SolveTSP >::value();
  }
  static const char* value(const ::lkh_tsp_solver::SolveTSPResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lkh_tsp_solver::SolveTSPResponse> should match
// service_traits::DataType< ::lkh_tsp_solver::SolveTSP >
template<>
struct DataType< ::lkh_tsp_solver::SolveTSPResponse>
{
  static const char* value()
  {
    return DataType< ::lkh_tsp_solver::SolveTSP >::value();
  }
  static const char* value(const ::lkh_tsp_solver::SolveTSPResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LKH_TSP_SOLVER_MESSAGE_SOLVETSP_H
