// Generated by gencpp from file lkh_mtsp_solver/SolveMTSP.msg
// DO NOT EDIT!


#ifndef LKH_MTSP_SOLVER_MESSAGE_SOLVEMTSP_H
#define LKH_MTSP_SOLVER_MESSAGE_SOLVEMTSP_H

#include <ros/service_traits.h>


#include <lkh_mtsp_solver/SolveMTSPRequest.h>
#include <lkh_mtsp_solver/SolveMTSPResponse.h>


namespace lkh_mtsp_solver
{

struct SolveMTSP
{

typedef SolveMTSPRequest Request;
typedef SolveMTSPResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SolveMTSP
} // namespace lkh_mtsp_solver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lkh_mtsp_solver::SolveMTSP > {
  static const char* value()
  {
    return "5b562e6076c8d155d3ad455cb6275b9e";
  }

  static const char* value(const ::lkh_mtsp_solver::SolveMTSP&) { return value(); }
};

template<>
struct DataType< ::lkh_mtsp_solver::SolveMTSP > {
  static const char* value()
  {
    return "lkh_mtsp_solver/SolveMTSP";
  }

  static const char* value(const ::lkh_mtsp_solver::SolveMTSP&) { return value(); }
};


// service_traits::MD5Sum< ::lkh_mtsp_solver::SolveMTSPRequest> should match
// service_traits::MD5Sum< ::lkh_mtsp_solver::SolveMTSP >
template<>
struct MD5Sum< ::lkh_mtsp_solver::SolveMTSPRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lkh_mtsp_solver::SolveMTSP >::value();
  }
  static const char* value(const ::lkh_mtsp_solver::SolveMTSPRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lkh_mtsp_solver::SolveMTSPRequest> should match
// service_traits::DataType< ::lkh_mtsp_solver::SolveMTSP >
template<>
struct DataType< ::lkh_mtsp_solver::SolveMTSPRequest>
{
  static const char* value()
  {
    return DataType< ::lkh_mtsp_solver::SolveMTSP >::value();
  }
  static const char* value(const ::lkh_mtsp_solver::SolveMTSPRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lkh_mtsp_solver::SolveMTSPResponse> should match
// service_traits::MD5Sum< ::lkh_mtsp_solver::SolveMTSP >
template<>
struct MD5Sum< ::lkh_mtsp_solver::SolveMTSPResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lkh_mtsp_solver::SolveMTSP >::value();
  }
  static const char* value(const ::lkh_mtsp_solver::SolveMTSPResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lkh_mtsp_solver::SolveMTSPResponse> should match
// service_traits::DataType< ::lkh_mtsp_solver::SolveMTSP >
template<>
struct DataType< ::lkh_mtsp_solver::SolveMTSPResponse>
{
  static const char* value()
  {
    return DataType< ::lkh_mtsp_solver::SolveMTSP >::value();
  }
  static const char* value(const ::lkh_mtsp_solver::SolveMTSPResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LKH_MTSP_SOLVER_MESSAGE_SOLVEMTSP_H
