// Generated by gencpp from file lkh_mtsp_solver/SolveMTSPResponse.msg
// DO NOT EDIT!


#ifndef LKH_MTSP_SOLVER_MESSAGE_SOLVEMTSPRESPONSE_H
#define LKH_MTSP_SOLVER_MESSAGE_SOLVEMTSPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lkh_mtsp_solver
{
template <class ContainerAllocator>
struct SolveMTSPResponse_
{
  typedef SolveMTSPResponse_<ContainerAllocator> Type;

  SolveMTSPResponse_()
    : empty(0)  {
    }
  SolveMTSPResponse_(const ContainerAllocator& _alloc)
    : empty(0)  {
  (void)_alloc;
    }



   typedef uint8_t _empty_type;
  _empty_type empty;





  typedef boost::shared_ptr< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SolveMTSPResponse_

typedef ::lkh_mtsp_solver::SolveMTSPResponse_<std::allocator<void> > SolveMTSPResponse;

typedef boost::shared_ptr< ::lkh_mtsp_solver::SolveMTSPResponse > SolveMTSPResponsePtr;
typedef boost::shared_ptr< ::lkh_mtsp_solver::SolveMTSPResponse const> SolveMTSPResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator1> & lhs, const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator2> & rhs)
{
  return lhs.empty == rhs.empty;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator1> & lhs, const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lkh_mtsp_solver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f908f4c332be245b1a763195cf157ba";
  }

  static const char* value(const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f908f4c332be245ULL;
  static const uint64_t static_value2 = 0xb1a763195cf157baULL;
};

template<class ContainerAllocator>
struct DataType< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lkh_mtsp_solver/SolveMTSPResponse";
  }

  static const char* value(const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 empty\n"
;
  }

  static const char* value(const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.empty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SolveMTSPResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lkh_mtsp_solver::SolveMTSPResponse_<ContainerAllocator>& v)
  {
    s << indent << "empty: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.empty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LKH_MTSP_SOLVER_MESSAGE_SOLVEMTSPRESPONSE_H
