// Generated by gencpp from file exploration_manager/PairOptResponse.msg
// DO NOT EDIT!


#ifndef EXPLORATION_MANAGER_MESSAGE_PAIROPTRESPONSE_H
#define EXPLORATION_MANAGER_MESSAGE_PAIROPTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exploration_manager
{
template <class ContainerAllocator>
struct PairOptResponse_
{
  typedef PairOptResponse_<ContainerAllocator> Type;

  PairOptResponse_()
    : from_drone_id(0)
    , to_drone_id(0)
    , status(0)
    , stamp(0.0)  {
    }
  PairOptResponse_(const ContainerAllocator& _alloc)
    : from_drone_id(0)
    , to_drone_id(0)
    , status(0)
    , stamp(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _from_drone_id_type;
  _from_drone_id_type from_drone_id;

   typedef int32_t _to_drone_id_type;
  _to_drone_id_type to_drone_id;

   typedef int32_t _status_type;
  _status_type status;

   typedef double _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::exploration_manager::PairOptResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exploration_manager::PairOptResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PairOptResponse_

typedef ::exploration_manager::PairOptResponse_<std::allocator<void> > PairOptResponse;

typedef boost::shared_ptr< ::exploration_manager::PairOptResponse > PairOptResponsePtr;
typedef boost::shared_ptr< ::exploration_manager::PairOptResponse const> PairOptResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exploration_manager::PairOptResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exploration_manager::PairOptResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exploration_manager::PairOptResponse_<ContainerAllocator1> & lhs, const ::exploration_manager::PairOptResponse_<ContainerAllocator2> & rhs)
{
  return lhs.from_drone_id == rhs.from_drone_id &&
    lhs.to_drone_id == rhs.to_drone_id &&
    lhs.status == rhs.status &&
    lhs.stamp == rhs.stamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exploration_manager::PairOptResponse_<ContainerAllocator1> & lhs, const ::exploration_manager::PairOptResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exploration_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exploration_manager::PairOptResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exploration_manager::PairOptResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration_manager::PairOptResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exploration_manager::PairOptResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_manager::PairOptResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exploration_manager::PairOptResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exploration_manager::PairOptResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17778d18292b1daf26721edbd91a3ac7";
  }

  static const char* value(const ::exploration_manager::PairOptResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17778d18292b1dafULL;
  static const uint64_t static_value2 = 0x26721edbd91a3ac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::exploration_manager::PairOptResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exploration_manager/PairOptResponse";
  }

  static const char* value(const ::exploration_manager::PairOptResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exploration_manager::PairOptResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Success or failure due to inconsistent views\n"
"int32 from_drone_id\n"
"int32 to_drone_id\n"
"int32 status \n"
"float64 stamp\n"
;
  }

  static const char* value(const ::exploration_manager::PairOptResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exploration_manager::PairOptResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.from_drone_id);
      stream.next(m.to_drone_id);
      stream.next(m.status);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PairOptResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exploration_manager::PairOptResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exploration_manager::PairOptResponse_<ContainerAllocator>& v)
  {
    s << indent << "from_drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.from_drone_id);
    s << indent << "to_drone_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.to_drone_id);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "stamp: ";
    Printer<double>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXPLORATION_MANAGER_MESSAGE_PAIROPTRESPONSE_H
